[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
chainsensor  = "C8qdXZW4Ze7Zy9u4bJbzhbJThxZbE4vBGKjQexsaWXwP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
