export default () => ({
  BROKER_URL: process.env.BROKER_URL,
  SOLANA_RPC: process.env.SOLANA_RPC,
  SOLANA_HTTP: process.env.SOLANA_HTTP, // NEW: HTTP endpoint for transaction fetching
  SOLANA_WS: process.env.SOLANA_WS,
  SOLANA_KEYPAIR_JSON: process.env.SOLANA_KEYPAIR_JSON,
  WALRUS_URL: process.env.WALRUS_URL,
  SOLANA_PROGRAM_ID: process.env.SOLANA_PROGRAM_ID,
  MARKETPLACE_ADMIN_PUBKEY: process.env.MARKETPLACE_ADMIN_PUBKEY,
  MONGODB_URI: process.env.MONGODB_URI,
  //TUSKY_API_KEY: process.env.TUSKY_API_KEY,
  //TUSKY_URL: process.env.TUSKY_URL,
  SELLER_FEE_BASIS: process.env.SELLER_FEE_BASIS,
  USDC_MINT: process.env.USDC_MINT,
  MARKETPLACE_NAME: process.env.MARKETPLACE_NAME,
  CA_KEY_PATH: process.env.CA_KEY_PATH,
  CA_CERT_PATH: process.env.CA_CERT_PATH,
  BROKER_KEY_PATH: process.env.BROKER_KEY_PATH,
  BROKER_CERT_PATH: process.env.BROKER_CERT_PATH,
  BROKER_PORT: Number(process.env.BROKER_PORT),
  TLS_KEY_PATH: process.env.BROKER_KEY_PATH,
  TLS_CERT_PATH: process.env.BROKER_CERT_PATH,
  TLS_CA_PATH: process.env.CA_CERT_PATH,

  // NEW (Walrus HTTP)
  WALRUS_PUBLISHER_URL: process.env.WALRUS_PUBLISHER_URL,
  WALRUS_AGGREGATOR_URL: process.env.WALRUS_AGGREGATOR_URL,
  WALRUS_EPOCHS: process.env.WALRUS_EPOCHS,
  WALRUS_DELETABLE: process.env.WALRUS_DELETABLE,
  
  // Arcium configuration
  ARCIUM_MXE_PROGRAM_ID: process.env.ARCIUM_MXE_PROGRAM_ID,
  MXE_X25519_PUBKEY_B64: process.env.MXE_X25519_PUBKEY_B64,
  MINT_AUTHORITY_KEYPAIR_JSON: process.env.MINT_AUTHORITY_KEYPAIR_JSON,
  ARCIUM_CLUSTER_PUBKEY: process.env.ARCIUM_CLUSTER_PUBKEY,
  ARCIUM_EXECUTING_POOL_PUBKEY: process.env.ARCIUM_EXECUTING_POOL_PUBKEY,
  ARCIUM_CLOCK_PUBKEY: process.env.ARCIUM_CLOCK_PUBKEY,
  ARCIUM_FEE_POOL_ACCOUNT: process.env.ARCIUM_FEE_POOL_ACCOUNT,
  ARCIUM_ACCURACY_CIRCUIT_URL: process.env.ARCIUM_ACCURACY_CIRCUIT_URL,
  ARCIUM_ACCURACY_CIRCUIT_HASH: process.env.ARCIUM_ACCURACY_CIRCUIT_HASH, // e.g., JSON array of 32 bytes

  // NEW: Accuracy computation configuration
  ACCURACY_WINDOW_MS: process.env.ACCURACY_WINDOW_MS || '300000', // 5 minutes default
  ACCURACY_TRIGGER_THRESHOLD: process.env.ACCURACY_TRIGGER_THRESHOLD || '0.5',
  
  // NEW: Redis configuration for BullMQ
  REDIS_HOST: process.env.REDIS_HOST || 'localhost',
  REDIS_PORT: process.env.REDIS_PORT || '6379',
  REDIS_PASSWORD: process.env.REDIS_PASSWORD,
  REDIS_DB: process.env.REDIS_DB || '0',
  REDIS_URL: process.env.REDIS_URL, // Alternative: full Redis URL
});
