[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = true

[programs.localnet]
chain_sensors = "D1hTFh5zn3q5ZAN9UQKePqfgk9cTYrfJsjkRYk589Duz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor build && yarn ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/home/reda-37/yo/ChainSensors-V1/chain_sensors/artifacts/arcium_program_0.2.0.so"

[test.validator]
url = "http://127.0.0.1:8890"
